version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: plmoknijb
      MYSQL_DATABASE: eannovate
      MYSQL_USER: ubaid
      MYSQL_PASSWORD: plmoknijb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
